# Generated by Django 4.1.5 on 2023-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
        ),
    ]
